# Generated by Django 6.0.7 on 2026-07-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('TIMEOUT', 'Timeout'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('response_time', models.PositiveIntegerField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='servers.server')),
            ],
        ),
    ]
