# Generated by Django 6.0.7 on 2026-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_healthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
